import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const tahoma = localFont({
  src: [
    {
      path: "../fonts/TahomaA.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/TahomaA.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-tahoma",
  display: "swap",
});
const franklinGothic = localFont({
  src: [
    {
      path: "../fonts/FranklinGothicITALIC.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/FranklinGothicITALIC.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-franklinGothic",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${tahoma.className} ${franklinGothic.className} antialiased w-screen  h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
